name: CD

on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: "Build and release the Rhino Plugin"
    runs-on: windows-latest

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
  
      - name: Compile  
        working-directory: src/Ladybug.Grasshopper
        run: |
          dotnet restore
          msbuild /p:Configuration=Release /restore
          ls bin -R

      - name: Zip Build Artifact
        run: |
          Compress-Archive -U -Path src\Ladybug.Grasshopper\bin\net45\* -DestinationPath LadybugGrasshopper
          ls

      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}